-- Sync all columns that exist in Prisma schema but may be missing in DB
-- ADDITIVE ONLY — no drops, no renames, no data loss

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS refresh_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;

-- roles
ALTER TABLE roles ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- permissions
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS key VARCHAR(255);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS parent_key VARCHAR(255);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS parent_id INTEGER;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- feedbacks
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS source VARCHAR(50);
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS facility_id VARCHAR(255);
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS survey_key VARCHAR(255);
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- posts
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

-- banners
ALTER TABLE banners ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS link_url TEXT;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- surveys
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS date_from DATE;
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS date_to DATE;
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS form_ids TEXT DEFAULT '[]';
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- forms
ALTER TABLE forms ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- work_schedules
ALTER TABLE work_schedules ADD COLUMN IF NOT EXISTS license_plate VARCHAR(20);
ALTER TABLE work_schedules ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE work_schedules ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE work_schedules ADD COLUMN IF NOT EXISTS presider_id INTEGER;

-- trading_facilities
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS certificate_number VARCHAR(100);
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS person_in_charge VARCHAR(255);
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS facility_type VARCHAR(100);
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS trading_type VARCHAR(100);
ALTER TABLE trading_facilities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
